Update coverity-check-touchIntercom.yaml

diff --git a/.github/workflows/coverity-check-touchIntercom.yaml b/.github/workflows/coverity-check-touchIntercom.yaml
--- a/.github/workflows/coverity-check-touchIntercom.yaml
+++ b/.github/workflows/coverity-check-touchIntercom.yaml
@@ -116,8 +116,23 @@ jobs:
           APP_REVISION=`git rev-parse --short HEAD`;
 
           ${CSA_DIR}/bin/cov-build --config ${COVERITY_CONFIG_XML} --dir ${COVERITY_INTERMEDIATE} ./gradlew build
+          
+          ${CSA_DIR}/bin/cov-analyze --all --dir ${COVERITY_INTERMEDIATE} --wait-for-license
+          cov_commit="${CSA_DIR}/bin/cov-commit-defects --url https://${CIM_USER}:${CIM_PASSWD}@${{ env.CIM_SERVER }} --ssl --stream ${STREAM}_low --dir ${COVERITY_INTERMEDIATE} --version ${APP_REVISION}";
+
+          max_try_count=10;
+          while ! ${cov_commit} && [ $max_try_count -ne 0 ]; do
+              echo "Remaining  try-count : ${max_try_count}";
+              max_try_count=$((max_try_count-1)); 
+              sleep 120;
+              if [ $max_try_count -eq "0" ] ; then
+                  echo "fail cov-commit";
+                  exit 1;
+              fi
+          done
+
           ${CSA_DIR}/bin/cov-analyze --aggressiveness-level high --all --dir ${COVERITY_INTERMEDIATE} --wait-for-license
-          cov_commit="${CSA_DIR}/bin/cov-commit-defects --url https://${CIM_USER}:${CIM_PASSWD}@${{ env.CIM_SERVER }} --ssl --stream ${STREAM} --dir ${COVERITY_INTERMEDIATE} --version ${APP_REVISION}";
+          cov_commit="${CSA_DIR}/bin/cov-commit-defects --url https://${CIM_USER}:${CIM_PASSWD}@${{ env.CIM_SERVER }} --ssl --stream ${STREAM}_high --dir ${COVERITY_INTERMEDIATE} --version ${APP_REVISION}";
 
           max_try_count=10;
           while ! ${cov_commit} && [ $max_try_count -ne 0 ]; do
