ci: mcp-9757 배포 리뉴얼 작업 진행

diff --git a/.github/workflows/qa_gitops-release.yaml b/.github/workflows/qa_gitops-release.yaml
--- a/.github/workflows/qa_gitops-release.yaml
+++ b/.github/workflows/qa_gitops-release.yaml
@@ -30,6 +30,11 @@ on:
         description: "Environment name for tagging"
         type: string
         default: "dev"
+      version_file_path:
+        required: false
+        description: "Path to the yaml file described all version of application"
+        type: string
+        default: "qa_version.yaml"
       region:
         required: false
         description: "aws region"
@@ -61,7 +66,7 @@ permissions: write-all
 jobs:
   gitops-release:
     runs-on: ubuntu-latest
-    environment: 
+    environment:
       name: ${{ inputs.environment_name }}
     name: GitOps Release
     steps:
@@ -85,39 +90,48 @@ jobs:
               .images[0].newTag = "${{ inputs.image_tag }}"
             ' ./gitops/${{ inputs.application_name }}/env/${{ vars.ENV }}/kustomization.yaml
 
-      - name: Update server version.json information
+      - name: Update version information
+        if: ${{ inputs.application_name }} != ""
         uses: mikefarah/yq@v4.34.2
         with:
           cmd: |
-            if [[ "${{ inputs.application_name }}" == *front* || "${{ inputs.application_name }}" == "mopl-admin" ]]; then
-              echo "Frontend application detected: ${{ inputs.application_name }}"
-              yq -i '.FrontendVersion["${{ inputs.application_name }}"] = "${{ inputs.image_tag }}"' ./gitops/qa_version.json
-            else
-              echo "Backend application detected: ${{ inputs.application_name }}"
-              yq -i '.BackendVersion["${{ inputs.application_name }}"] = "${{ inputs.image_tag }}"' ./gitops/qa_version.json
-            fi
+            yq -i '.${{ inputs.application_name }}.image-tag = "${{ inputs.image_tag }}"' ./gitops/${{ inputs.version_file_path }}
 
-
-      - name: Create QA GitOps Pull Request
-        uses: peter-evans/create-pull-request@v6
+      - name: Update BE server version.json information
+        if: ${{ inputs.application_name != 'admin-frontend' && inputs.application_name != 'mopl-admin' && inputs.application_name != 'store-front' }}
+        uses: mikefarah/yq@v4.34.2
         with:
-          path: ./gitops
-          token: ${{ secrets.GH_MANAGEPACKAGE_TOKEN }}
-          commit-message: |
-            chore: update ${{ inputs.application_name }} image tag to ${{ inputs.image_tag }}
-          branch: |
-            gitops/${{ inputs.application_name }}-${{ inputs.image_tag }}
-          title: |
-            Update QA image tag for ${{ inputs.application_name }}: ${{ inputs.image_tag }}
-          body: |
-            This PR updates the deployment configuration for ${{ inputs.application_name }}.
+          cmd: |
+            yq -i '.["BackendVersion"].["${{ inputs.application_name }}"] = "${{ inputs.image_tag }}"' ./gitops/qa_version.json       
 
-            - Image name: `${{ inputs.image_name }}`
-            - Image tag: `${{ inputs.image_tag }}`
-            - Environment: `${{ vars.ENV }}`
+      - name: Update FN server version.json information
+        if: ${{ inputs.application_name == 'admin-frontend' || inputs.application_name == 'mopl-admin' || inputs.application_name == 'store-front' }}
+        uses: mikefarah/yq@v4.34.2
+        with:
+          cmd: |
+            yq -i '.["FrontendVersion"].["${{ inputs.application_name }}"] = "${{ inputs.image_tag }}"' ./gitops/qa_version.json       
 
-            Please review and merge after verification.
-          base: main
-          labels: |
-            qa_deploy
-          delete-branch: true
+      - name: Commit changes
+        working-directory: ./gitops
+        run: |
+          git config user.name "GitHub Actions Bot" && \
+          git config user.email "<>" && \
+          git add --all
+          git commit -m "chore: update ${{ inputs.image_name }} image tag as ${{ inputs.image_tag }}" && \
+          # Push logic with retries
+          for i in {1..5}; do
+            git pull origin main --rebase
+            if git push origin main; then
+              echo "Push successful"
+              break
+            else
+              echo "Push failed, retrying ($i/5)..."
+              sleep 5
+            fi
+          done
+
+          # If the push still fails after retries
+          if [ $? -ne 0 ]; then
+            echo "Push failed after multiple attempts"
+            exit 1
+          fi
